# Generated by Django 5.1.7 on 2025-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('DF', 'تعلیق'), ('PB', 'انتشار'), ('RJ', 'رد کردن نظر')], default='DF', max_length=2, verbose_name='وضعیت'),
        ),
    ]
