# Generated by Django 5.1.7 on 2025-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('hookahs', 'قلیان\u200cها'), ('drinks', 'نوشیدنی\u200cها'), ('foods', 'غذاها')], default='foods', max_length=20),
        ),
    ]
