# Generated by Django 5.1.7 on 2025-03-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_image_category_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'منو', 'verbose_name_plural': 'منو'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
    ]
